### ISSUE TITLE
Contributor images not appearing in readme

### ISSUE THREAD

**Issue by Vardhan-ysh** [AOSSIE-Org/Monumento#208]
### 🐛 Describe the bug

Contributor images not appearing clearly in readme

![image](https://github.com/user-attachments/assets/89b3fdc2-eff2-4e40-9c87-3e3a4d42cc37)

**Comment by Vardhan-ysh** [comment]
I can fix this issue.

**Comment by HelloSniperMonkey** [comment]
<img width="1912" alt="Screenshot 2024-12-23 at 7 27 24 PM" src="https://github.com/user-attachments/assets/0f6d10d9-349c-45ae-8a7f-f876cb333921" />
<img width="1912" alt="Screenshot 2024-12-23 at 7 27 40 PM" src="https://github.com/user-attachments/assets/072c9b8f-8feb-4bb7-abdb-14abebb2ebe8" />
i don't see the issue here 

can you provide the steps to reproduce the bug ?

**Comment by Vardhan-ysh** [comment]
Yeah, I think that was some issues on my end
